version: '3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=pass123
    networks:
      - postgres

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - ./rabbitmq.env

  pgadmin:
    links:
      - postgres:postgres
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=markflerko@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pass123
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
