version: '3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=pass123
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=markflerko@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pass123
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
